### ISSUE TITLE
Permissions pane causes 401 with PUT on CSS

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solidos#113] opened 2022-01-26 15:37 UTC
When using the permissions pane to change an ACL file hosted on CSS, SolidOS will send a `PUT` request _without_ an `Authorization` header, causing CSS to reply with 401.

In constrast, opening that same ACL file in the source pane, will generate the correct `PUT` request with the `Authorization` header, resulting in a 2xx.

This can be replicated with the [Mashlib recipe](https://github.com/solid/community-server-recipes/tree/main/mashlib).

**Comment by timbl** [comment] 2022-01-27 14:15
Looks like the wrong fetch being called

**Comment by timbl** [comment] 2022-01-27 14:16
But strange that NSS doesn't have the problem

**Comment by timbl** [comment] 2022-01-27 14:27
It uses `UpdateManager.put` which uses `webOperation` which uses `Fetcher._fetch` which  should be good if you are logged in .. nothing obvious

**Comment by bourgeoa** [comment] 2022-01-29 23:13
I can reproduce the 401 error with SolidOS web app on https://solidweb.me (CSS)

![image](https://user-images.githubusercontent.com/2218470/151680523-0a518a76-ba61-4193-9959-e011dee39c61.png)

**Comment by bourgeoa** [comment] 2022-01-29 23:49
The PUT do not use Session.fetch() but browser-ponyfill fetch.

**Comment by RubenVerborgh** [comment] 2022-01-30 18:46
> The PUT do not use Session.fetch() but browser-ponyfill fetch.

What line is that?

This is a bug in the code; the reason it works with NSS is (non-standard) cookies.

**Comment by jeff-zucker** [comment] 2022-01-30 20:35
AFAIK, the only place in the SolidOS stack where browser-ponyfill.fetch is used is in @inrupt/solid-client-authn-core/dist/login/oidc/redirectHandler/redirectHandler.js in this line : 
```
    const jwksResponse = await (0, cross_fetch_1.fetch)(jwksIri);  
```
In other words, it is part of Inrupt's login redirect process and only peripherally related to PUT and, unless I'm mistaken, is an Inrupt issue.  I'm not sure the browser-ponyfill fetch is even related to this permissions pane issue.

**Comment by bourgeoa** [comment] 2022-01-31 21:43
@timbl @SharonStrats 
The code is not using the solidLogic `store` but is creating a new graph : `newAClGraph = graph()` with I suppose a non authenticated fetch.
The code organization seems to need 2 stores to be able to duplicate the graph in certain situations.

I do not succeed to create a duplicate of the authenticate store. Could you look at it.
With this code I still have a 401
```
import { store } from '../logic'
......
public save (): Promise<void> {
       const newAClGraph = store
......
       const updater = newAClGraph?.updater // || new UpdateManager(newAClGraph)
```

**Comment by jeff-zucker** [comment] 2022-02-11 01:06
@bourgeoa the code there creates a new store (newACLGraph) and an upadater for it without specifying a fetch,  Which means you are correct that it uses the default cross-fetch.  So we don't need to do anything with the store, just with the fetcher for the updater.  This can be done by this sequence : 
```
  import {fetcher} from 'rdflib';
  const newACLGraph = graph() 
  const fetcher = fetcher(newACLGraph,{fetch:this.store.fetcher._fetch})
const updater ...
```
That will create a new store and an updater for it that uses the fetch from the existing store.  I believe that is the desired effect.

**Comment by bourgeoa** [comment] 2022-02-16 15:07
Adding the authorized fetch enable creation and edit on creation.
when trying to edit an existing ACL the 401 error comes again. Weird.
When the error is there there is no way to remove the 401 error except by reloading the page.

**Comment by bourgeoa** [comment] 2022-02-17 16:21
@angelo-v 
> Adding the authorized fetch enable creation and edit on creation.
when trying to edit an existing ACL the 401 error comes again. Weird.
When the error is there there is no way to remove the 401 error except by reloading the page.

The only think I did is add here
https://github.com/solid/solid-ui/blob/48f3ebed3572bc099bfcd5b770fd5a3f4d738795/src/acl/access-controller.ts#L230
```
    newAClGraph.fetcher = fetcher(newAClGraph, { fetch: this.store.fetcher._fetch })

```
This add an authenticated fetch to the newAClGraph.
I use the tryMoveAuth branch, but the problem should not be branch depending. It existed before.

My analyse is that for any reason loading an existing resource ACL to the store does load in a store with no-authenticated.fetch

**Comment by timbl** [comment] 2022-02-19 15:37
When those bits were written, we used to think about making a Fetcher.  In fact we had the shortcut fetcher() to do it easily. Now we just make a LiveStore which has automatically has a Fetcher and an UpdateManager attached to it. 
Should we change the default _fetch for any new Fetcher?

**Comment by jeff-zucker** [comment] 2022-02-19 16:20
I believe so, yes.  It should check the window.solidFetch to see if the user set a global fetch method and then check the existing _fetch and use that.  I can't see any advantage to ignoring the user's definition of a fetch method and lots of reasons to  honor it.

**Comment by RubenVerborgh** [comment] 2022-02-21 19:58
> I wonder why the problem did not show up on NSS.

Cookie-based auth is also active (which CSS and ESS don't use because of security concerns).

**Comment by jeff-zucker** [comment] 2022-02-21 21:23
@RubenVerborgh and @timbl - I don't believe it has to do with cookies.  If you try the script below, you see that I login to NSS and then do an unauthenticated fetch and get back a 401 even though the cookie is active.  
```html
<!DOCTYPE html><html><head>
  <meta charset="UTF-8" />
</head><body>
  <span id="webId"></span>
  <input id="oidc" value="https://solidcommunity.net" style="width:24em" />
  <button id="loginButton">Login</button>
  <button id="logoutButton">Logout</button>

<script src="https://cdn.jsdelivr.net/npm/@inrupt/solid-client-authn-browser@1.11.2/dist/solid-client-authn.bundle.js">
</script>
<script>

const iscan = solidClientAuthentication;
var session = iscan.getDefaultSession();

const loginButton = document.querySelector("#loginButton");
const logoutButton = document.querySelector("#logoutButton");
const webIdArea = document.querySelector("#webId");
loginButton.onclick = ()=> { 
  return iscan.login({
    oidcIssuer: document.getElementById("oidc").value,
    redirectUrl: window.location.href,
    clientName: "Minimal login/logout"
  });
};
logoutButton.onclick = async ()=> { 
  await session.logout();
  showLoginStatus();
};
async function handleRedirectAfterLogin() {
  await iscan.handleIncomingRedirect();
  showLoginStatus();
}
async function showLoginStatus() {
  session = iscan.getDefaultSession();
  if (session.info.isLoggedIn) {
    loginButton.style.display = "none";
    logoutButton.style.display = "inline-block";
    webId.innerHTML = `Logged in as ${session.info.webId}`;
    const privateThing='https://jeff-zucker.solidcommunity.net/private/testput.txt';
    let response = await window.fetch(privateThing,{
      method:"PUT",
      headers: {"content-type":"text/plain"},
      body: "some words",
    })
    webId.innerHTML+="Response to un-authenticated PUT : "+response.status;
  }
  else {
    loginButton.style.display =  "inline-block";
    logoutButton.style.display = "none";
    webId.innerHTML = `Not logged in.`;
  }
}
handleRedirectAfterLogin();
</script></body></html>
```

**Comment by RubenVerborgh** [comment] 2022-02-21 23:08
> ```
>     let response = await window.fetch(privateThing,{
>       method:"PUT",
>       headers: {"content-type":"text/plain"},
>       body: "some words",
>     })
> ```

is missing `credentials: "include"` which rdflib used to set at some point

**Comment by jeff-zucker** [comment] 2022-02-21 23:28
Same results when I add that.  In any case, NSS does NOT accept its cookie
as proof of login when it receives an unauthenticated PUT.  Unless I'm
mistaken, this means the cookie is not the reason NSS fails to give a 401
when CSS gave one.

**Comment by bourgeoa** [comment] 2022-03-03 17:22
closed with https://github.com/solid/solid-ui/pull/476/files

**Closed by bourgeoa** 2022-03-03 17:22 UTC
Labels: bug
